#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: canary
rules:
- apiGroups: ["flagger.app", "apiextensions.k8s.io/v1"]
  resources: ["canaries", "customresourcedefinitions"]
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: canary
subjects:
- kind: ServiceAccount
  name: default
  namespace: #@ data.values.name