#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa
rules:
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpa
subjects:
  - kind: ServiceAccount
    name: default
    namespace: #@ data.values.name