#@ load("@ytt:data", "data")
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-and-notify-pipeline
  labels:
    apps.tanzu.vmware.com/intent: notify
spec:
  params:
    - name: source-url
    - name: source-revision
    - name: deliverable-name
    - name: deliverable-namespace
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: deliverable-name
          value: $(params.deliverable-name)
        - name: deliverable-namespace
          value: $(params.deliverable-namespace)
        - name: environment
          value: dev
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        results:
          - description: git-sha
            name: git-sha
            type: string
        steps:
          - name: test
            image: cxscssa.azurecr.io/utils/module-detector-pipeline-image:0.5.0
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m

              cd config/$(params.deliverable-namespace)/$(params.deliverable-name)/$(params.env)
              
              yaml_file="delivery.yml"
              
              git_sha_value=$(yq e '. | select(.kind == "Deployment") | .spec.template.metadata.annotations."apps.tanzu.vmware.com/git-sha"' "$yaml_file")
              echo $git_sha_value > $(results.git-sha.path)
    - name: slack
      params:
        - name: webhook-secret
          value: webhook-secret
        - name: message
          value: "Source code commit sha - $(tasks.test.results.git-sha)"
      taskRef:
        name: send-to-webhook-slack