---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  annotations:
    tekton.dev/docker-0: cxscssa.azurecr.io/tap-workloads
spec:
  fromNamespace: tap-install