---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: store-ca-sert
spec:
  fromNamespace: metadata-store-secrets
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: store-auth-token
spec:
  fromNamespace: metadata-store-secrets