#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readsecrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readsecrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readsecrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: #@ data.values.name