#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readclusterbuilders
rules:
  - apiGroups:
    - kpack.io
    resources:
    - clusterbuilders
    - builders
    verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readclusterbuilders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readclusterbuilders
subjects:
  - kind: ServiceAccount
    name: default
    namespace: #@ data.values.name